# Generated by Django 4.2.17 on 2025-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('product_name', models.CharField(default='', max_length=1000)),
                ('category', models.CharField(blank=True, max_length=250)),
                (
                    'price',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='Количество',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ('nds_type', models.IntegerField(blank=True, default=None, null=True)),
                (
                    'nds_sum',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='Date created'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('receipt_date', models.DateTimeField()),
                ('number_receipt', models.IntegerField(default=None, null=True)),
                (
                    'nds10',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=60, null=True
                    ),
                ),
                (
                    'nds20',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=60, null=True
                    ),
                ),
                (
                    'operation_type',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 'Покупка'),
                            (2, 'Возврат средств за покупку'),
                            (3, 'Продажа\\Выигрыш'),
                            (4, 'Возврат выигрыша или продажи'),
                        ],
                        default=0,
                        null=True,
                    ),
                ),
                (
                    'total_sum',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ('manual', models.BooleanField(null=True)),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='Date created'
                    ),
                ),
            ],
            options={
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name_seller', models.CharField(max_length=255)),
                (
                    'retail_place_address',
                    models.CharField(
                        blank=True, default='Нет данных', max_length=1000, null=True
                    ),
                ),
                (
                    'retail_place',
                    models.CharField(
                        blank=True, default='Нет данных', max_length=1000, null=True
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name='Date created'
                    ),
                ),
            ],
        ),
    ]
