# Generated by Django 5.2.3 on 2025-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('receipts', '0004_alter_receipt_seller_alter_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='retail_place',
            field=models.CharField(
                blank=True, default='Нет данных', max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name='seller',
            name='retail_place_address',
            field=models.CharField(
                blank=True, default='Нет данных', max_length=1000, null=True
            ),
        ),
    ]
