# Generated by Django 6.0 on 2025-12-26 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0016_alter_account_currency'),
        ('receipts', '0005_alter_seller_retail_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_data', models.JSONField(help_text='JSON данные чека для редактирования', verbose_name='Данные чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(help_text='Время, после которого запись будет удалена', verbose_name='Дата истечения')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_receipts', to='finance_account.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Временный чек',
                'verbose_name_plural': 'Временные чеки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='receipts_pe_user_id_e9ac88_idx'), models.Index(fields=['expires_at'], name='receipts_pe_expires_21ada0_idx')],
            },
        ),
    ]
