# Generated by Django 6.0.1 on 2026-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_add_pending_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='number_receipt',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
