# Generated by Django 6.0.4 on 2026-05-03 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_pending_as_ready(apps, schema_editor):
    """Backfill: existing PendingReceipt rows already passed inference."""
    pending_model = apps.get_model('receipts', 'PendingReceipt')
    pending_model.objects.update(status='ready')


def noop_reverse(apps, schema_editor):
    """Reverse no-op: status field is dropped on rollback anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0017_alter_transfermoneylog_from_account_and_more"),
        ("receipts", "0007_alter_receipt_number_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptImageHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Хеш изображения чека",
                "verbose_name_plural": "Хеши изображений чеков",
            },
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="error_message",
            field=models.TextField(
                blank=True, default="", verbose_name="Сообщение об ошибке"
            ),
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="image_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pending_receipts/",
                verbose_name="Файл изображения",
            ),
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="image_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hex digest для дедупликации загрузок",
                max_length=64,
                verbose_name="Хеш файла изображения",
            ),
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("ready", "Готов к проверке"),
                    ("failed", "Ошибка обработки"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="task_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Идентификатор задачи Celery",
            ),
        ),
        migrations.RunPython(
            mark_existing_pending_as_ready,
            noop_reverse,
        ),
        migrations.AlterField(
            model_name="pendingreceipt",
            name="receipt_data",
            field=models.JSONField(
                blank=True,
                help_text="JSON данные чека для редактирования",
                null=True,
                verbose_name="Данные чека",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingreceipt",
            index=models.Index(
                fields=["user", "status"], name="receipts_pe_user_id_cff4f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingreceipt",
            index=models.Index(
                fields=["user", "image_hash"], name="receipts_pe_user_id_217bb2_idx"
            ),
        ),
        migrations.AddField(
            model_name="receiptimagehash",
            name="receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_hash_record",
                to="receipts.receipt",
            ),
        ),
        migrations.AddField(
            model_name="receiptimagehash",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_image_hashes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="receiptimagehash",
            index=models.Index(
                fields=["user", "image_hash"], name="receipts_re_user_id_d314d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptimagehash",
            constraint=models.UniqueConstraint(
                fields=("user", "image_hash"), name="uniq_user_image_hash"
            ),
        ),
    ]
