# Generated by Django 6.0.5 on 2026-05-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('receipts', '0009_seed_cleanup_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='seller',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='receipt_sellers',
                to='receipts.seller',
                verbose_name='seller',
            ),
        ),
    ]
