# Generated by Django 6.0.5 on 2026-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_alter_receipt_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
    ]
