# Generated by Django 6.0.7 on 2026-07-29 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0017_alter_transfermoneylog_from_account_and_more"),
        ("receipts", "0013_alter_pendingreceipt_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingreceipt",
            name="converted_receipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_pending_receipt",
                to="receipts.receipt",
            ),
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="fiscal_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingreceipt",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="adjustment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="receipt",
            name="fiscal_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pendingreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В обработке"),
                    ("ready", "Готов к проверке"),
                    ("ready_with_warning", "Готов с предупреждением"),
                    ("failed", "Ошибка обработки"),
                    ("converted", "Сохранён"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("fiscal_key__isnull", False),
                    ("status__in", ["processing", "ready", "ready_with_warning"]),
                ),
                fields=("user", "fiscal_key"),
                name="uniq_active_pending_user_fiscal_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fiscal_key__isnull", False)),
                fields=("user", "fiscal_key"),
                name="uniq_receipt_user_fiscal_key",
            ),
        ),
    ]
