# Generated by Django 6.0.7 on 2026-08-26 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0024_add_external_id_and_audit"),
        ("receipts", "0014_pendingreceipt_converted_receipt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="attention_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="receipt",
            name="requires_attention",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ReceiptProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "В обработке"),
                            ("completed", "Проведён"),
                            ("failed", "Ошибка обработки"),
                            ("duplicate", "Повторный чек"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True, null=True, upload_to="receipt_processing_logs/"
                    ),
                ),
                ("qr_raw", models.CharField(blank=True, default="", max_length=1024)),
                ("image_hash", models.CharField(blank=True, default="", max_length=64)),
                ("fiscal_key", models.CharField(blank=True, max_length=255, null=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_processing_logs",
                        to="finance_account.account",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_log",
                        to="receipts.receipt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_processing_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="receipts_re_user_id_fd00f8_idx"
                    ),
                    models.Index(
                        fields=["user", "image_hash"],
                        name="receipts_re_user_id_a08444_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("fiscal_key__isnull", False), ("status", "processing")
                        ),
                        fields=("user", "fiscal_key"),
                        name="uniq_active_processing_log_user_fiscal_key",
                    )
                ],
            },
        ),
    ]
