# Generated by Django 6.0.7 on 2026-08-29

from django.db import migrations


class Migration(migrations.Migration):
    """Merge product category and receipt processing migration branches."""

    dependencies = [
        ('receipts', '0015_productcategory_and_more'),
        (
            'receipts',
            '0015_receipt_attention_reason_receipt_requires_attention_and_more',
        ),
    ]

    operations = []
