# Generated by Django 6.0.7 on 2026-08-29 14:50

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add pg_trgm-backed writing-match search and the pinned name mapping."""

    dependencies = [
        ('receipts', '0016_merge_product_categories_and_processing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='ProductNameCategoryMapping',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('normalized_product_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['product_name'],
                name='receipts_product_name_trgm_gin',
                opclasses=['gin_trgm_ops'],
            ),
        ),
        migrations.AddField(
            model_name='productnamecategorymapping',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='name_mappings',
                to='receipts.productcategory',
            ),
        ),
        migrations.AddField(
            model_name='productnamecategorymapping',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='product_name_category_mappings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='productnamecategorymapping',
            constraint=models.UniqueConstraint(
                fields=('user', 'normalized_product_name'),
                name='unique_user_normalized_product_name_mapping',
            ),
        ),
    ]
