# Generated by Django 6.0.7 on 2026-08-29 15:24

import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    """Add pgvector-backed embeddings for semantic product category matching."""

    dependencies = [
        ('receipts', '0017_pinned_name_category_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='product',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['name_embedding'], m=16, name='receipts_product_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
