# Generated by Django 6.0.7 on 2026-09-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0021_remove_pending_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptprocessinglog",
            name="error_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image_missing", "Нет изображения чека"),
                    ("qr_not_found", "QR-код не найден"),
                    ("qr_invalid", "QR-код не похож на чек ФНС"),
                    ("fns_unavailable", "ФНС недоступна"),
                    ("fns_rate_limited", "ФНС ограничила частоту"),
                    ("fns_auth_failed", "Ошибка авторизации в ФНС"),
                    ("fns_bad_response", "Неожиданный ответ ФНС"),
                    ("receipt_invalid", "Данные чека не прошли проверку"),
                    ("line_invalid", "Некорректная товарная строка"),
                    ("total_invalid", "Некорректная итоговая сумма"),
                    ("timed_out", "Превышено время обработки"),
                    ("unexpected", "Непредвиденная ошибка"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="receiptprocessinglog",
            name="error_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qr", "Чтение QR-кода"),
                    ("claim", "Захват фискального ключа"),
                    ("fns", "Запрос в ФНС"),
                    ("map", "Разбор ответа ФНС"),
                    ("validate", "Проверка данных чека"),
                    ("create", "Проведение чека"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
