# Generated by Django 4.2.17 on 2025-02-09 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance_account', '0001_initial'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='category_expense_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expense_accounts',
                to='finance_account.account',
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expense_categories',
                to='expense.expensecategory',
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expense_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['name'], name='expense_exp_name_f951bb_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expense_exp_date_5e5d86_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['amount'], name='expense_exp_amount_ce8d33_idx'),
        ),
    ]
