# Generated by Django 5.2.3 on 2025-06-29 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expense', '0002_initial'),
        ('finance_account', '0006_alter_account_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(
                fields=['user', 'date'], name='expense_exp_user_id_31bf86_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(
                fields=['user', 'category'], name='expense_exp_user_id_0b88e2_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(
                fields=['user', 'account'], name='expense_exp_user_id_59bf09_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(
                fields=['date', 'amount'], name='expense_exp_date_2cd64b_idx'
            ),
        ),
    ]
