version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-for-testing
    volumes:
      - ./logs:/app/logs
    command: [".venv/bin/granian", "--interface", "asgi", "config.asgi:application", "--port", "8001", "--host", "0.0.0.0", "--reload"]
