# Generated by Django 5.2.3 on 2025-06-23 13:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0002_initial'),
        ('expense', '0002_initial'),
        ('income', '0003_alter_income_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='planning',
            name='category_expense',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='expense.expensecategory',
            ),
        ),
        migrations.AddField(
            model_name='planning',
            name='category_income',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='income.incomecategory',
            ),
        ),
        migrations.AddField(
            model_name='planning',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='planning',
            name='type',
            field=models.CharField(
                choices=[('expense', 'Расход'), ('income', 'Доход')],
                default='expense',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='datelist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together={
                ('user', 'category_expense', 'category_income', 'date', 'type')
            },
        ),
    ]
