# Generated by Django 5.2.4 on 2025-07-10 15:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0003_planning_amount_planning_category_expense_and_more'),
        ('expense', '0004_alter_expensecategory_name_and_more'),
        ('income', '0005_income_income_inco_date_2adb4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datelist',
            options={
                'ordering': ['-date'],
                'verbose_name': 'Список дат',
                'verbose_name_plural': 'Списки дат',
            },
        ),
        migrations.AlterModelOptions(
            name='planning',
            options={
                'ordering': ['-date'],
                'verbose_name': 'Планирование',
                'verbose_name_plural': 'Планирования',
            },
        ),
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='datelist',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Когда запись была создана',
                null=True,
                verbose_name='Дата создания',
            ),
        ),
        migrations.AlterField(
            model_name='datelist',
            name='date',
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text='Дата планирования',
                verbose_name='Дата',
            ),
        ),
        migrations.AlterField(
            model_name='datelist',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, для которого ведется список дат',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='budget_date_lists',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='amount',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Планируемая сумма',
                max_digits=12,
                verbose_name='Сумма',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='category_expense',
            field=models.ForeignKey(
                blank=True,
                help_text='Категория расхода (если применимо)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='plannings_expense',
                to='expense.expensecategory',
                verbose_name='Категория расхода',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='category_income',
            field=models.ForeignKey(
                blank=True,
                help_text='Категория дохода (если применимо)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='plannings_income',
                to='income.incomecategory',
                verbose_name='Категория дохода',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Когда запись была создана',
                null=True,
                verbose_name='Дата создания',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text='Дата планирования',
                verbose_name='Дата',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='type',
            field=models.CharField(
                choices=[('expense', 'Расход'), ('income', 'Доход')],
                db_index=True,
                default='expense',
                help_text='Тип планирования: расход или доход',
                max_length=10,
                verbose_name='Тип',
            ),
        ),
        migrations.AlterField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь, для которого ведется планирование',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='plannings',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddIndex(
            model_name='datelist',
            index=models.Index(
                fields=['user', 'date'], name='budget_date_user_id_4ab954_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='planning',
            index=models.Index(
                fields=['user', 'date', 'type'], name='budget_plan_user_id_409634_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.UniqueConstraint(
                fields=('user', 'category_expense', 'category_income', 'date', 'type'),
                name='unique_planning_per_user_category_date_type',
            ),
        ),
    ]
