# Generated by Django 5.2.8 on 2025-11-10 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_datelist_options_alter_planning_options_and_more'),
        ('expense', '0004_alter_expensecategory_name_and_more'),
        ('income', '0006_alter_incomecategory_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planning',
            name='unique_planning_per_user_category_date_type',
        ),
        migrations.RemoveIndex(
            model_name='planning',
            name='budget_plan_user_id_409634_idx',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='type',
            new_name='planning_type',
        ),
        migrations.AddIndex(
            model_name='planning',
            index=models.Index(fields=['user', 'date', 'planning_type'], name='budget_plan_user_id_2ee358_idx'),
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.UniqueConstraint(fields=('user', 'category_expense', 'category_income', 'date', 'planning_type'), name='unique_planning_per_user_category_date_type'),
        ),
    ]
