# Generated by Django 6.0.2 on 2026-02-25 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "budget",
            "0005_remove_planning_unique_planning_per_user_category_date_type_and_more",
        ),
        ("expense", "0005_alter_expense_amount"),
        ("income", "0007_alter_income_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="planning",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category_expense__isnull", False),
                        ("planning_type", "expense"),
                    ),
                    models.Q(
                        ("category_income__isnull", False), ("planning_type", "income")
                    ),
                    _connector="OR",
                ),
                name="planning_category_matches_type",
            ),
        ),
    ]
