# Generated by Django 5.1.7 on 2025-04-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance_account', '0004_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(
                choices=[
                    ('C', 'Кредитный счёт'),
                    ('D', 'Дебетовый счёт'),
                    ('CASH', 'Наличные'),
                ],
                default='Дебетовый счёт',
                verbose_name='Тип счёта',
            ),
        ),
    ]
