# Generated by Django 5.2.4 on 2025-07-11 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance_account', '0009_account_grace_period_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(
                choices=[
                    ('RUB', 'Российский рубль'),
                    ('USD', 'Доллар США'),
                    ('EUR', 'Евро'),
                    ('GBP', 'Британский фунт'),
                    ('CZK', 'Чешская крона'),
                    ('PLN', 'Польский злотый'),
                    ('TRY', 'Турецкая лира'),
                    ('CNH', 'Китайский юань'),
                ],
                default='RUB',
                help_text='Валюта счёта (например, RUB, USD)',
                verbose_name='Валюта',
            ),
        ),
        migrations.AlterField(
            model_name='transfermoneylog',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='Дата и время создания'
            ),
        ),
        migrations.AlterField(
            model_name='transfermoneylog',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text='Дополнительная информация о переводе',
                verbose_name='Примечания',
            ),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='account_user_id_5ee0be_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['type_account'], name='account_type_ac_7e6601_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['currency'], name='account_currenc_d95126_idx'),
        ),
        migrations.AddIndex(
            model_name='transfermoneylog',
            index=models.Index(fields=['user'], name='finance_acc_user_id_bd65fe_idx'),
        ),
        migrations.AddIndex(
            model_name='transfermoneylog',
            index=models.Index(
                fields=['from_account'], name='finance_acc_from_ac_604205_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transfermoneylog',
            index=models.Index(
                fields=['to_account'], name='finance_acc_to_acco_66e485_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='transfermoneylog',
            index=models.Index(
                fields=['exchange_date'], name='finance_acc_exchang_0e6111_idx'
            ),
        ),
    ]
