# Generated by Django 5.2.7 on 2025-10-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0013_alter_account_bank_alter_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name_account'], 'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='transfermoneylog',
            options={'ordering': ['-exchange_date'], 'verbose_name': 'Лог перевода денег', 'verbose_name_plural': 'Логи переводов денег'},
        ),
    ]
