# Generated by Django 5.2.8 on 2025-11-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0014_alter_account_options_alter_transfermoneylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время обновления'),
        ),
        migrations.AddField(
            model_name='transfermoneylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время обновления'),
        ),
    ]
