# Generated by Django 6.0.2 on 2026-02-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0016_alter_account_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfermoneylog",
            name="from_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_account",
                to="finance_account.account",
            ),
        ),
        migrations.AlterField(
            model_name="transfermoneylog",
            name="to_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="to_account",
                to="finance_account.account",
            ),
        ),
    ]
