# Generated by Django 6.0.7 on 2026-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0017_alter_transfermoneylog_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('Credit', 'Кредитный счёт'), ('Debit', 'Дебетовый счёт'), ('CreditCard', 'Кредитная карта'), ('DebitCard', 'Дебетовая карта'), ('CASH', 'Наличные'), ('Deposit', 'Вклад')], default='Debit', max_length=20, verbose_name='Тип счёта'),
        ),
    ]
