# Generated by Django 6.0.7 on 2026-08-02 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0018_alter_account_type_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код банка')),
                ('name', models.CharField(max_length=250, verbose_name='Название банка')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный банк')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, help_text='Только для личных банков пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_banks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_system', False)), fields=('name', 'user'), name='unique_bank_name_per_user')],
            },
        ),
    ]
