# Generated by Django 6.0.7 on 2026-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0022_add_bank_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Дата архивации"
            ),
        ),
    ]
