# Generated by Django 6.0.7 on 2026-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_account', '0023_account_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней сверки'),
        ),
    ]
