# Generated by Django 6.0.1 on 2026-02-01 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0016_alter_account_currency"),
        ("users", "0004_dashboardwidget"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatementUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="bank_statements/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("total_transactions", models.IntegerField(default=0)),
                ("processed_transactions", models.IntegerField(default=0)),
                ("income_count", models.IntegerField(default=0)),
                ("expense_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance_account.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statement_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Загрузка банковской выписки",
                "verbose_name_plural": "Загрузки банковских выписок",
                "ordering": ["-created_at"],
            },
        ),
    ]
