# Generated by Kilo on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_bankstatementupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
