# Generated by Kilo Code on 2026-05-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_family_memberships(apps, _schema_editor):
    group_model = apps.get_model('auth', 'Group')
    membership_model = apps.get_model('users', 'FamilyGroupMembership')
    for group in group_model.objects.prefetch_related('user_set'):
        users = list(group.user_set.order_by('id'))
        for index, user in enumerate(users):
            membership_model.objects.get_or_create(
                group=group,
                user=user,
                defaults={'role': 'owner' if index == 0 else 'viewer'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_user_theme_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInvite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('token', models.CharField(max_length=64, unique=True)),
                (
                    'role',
                    models.CharField(
                        choices=[('owner', 'Владелец'), ('viewer', 'Просмотр')],
                        default='viewer',
                        max_length=20,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='created_family_invites',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='family_invites',
                        to='auth.group',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Семейное приглашение',
                'verbose_name_plural': 'Семейные приглашения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyGroupMembership',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[('owner', 'Владелец'), ('viewer', 'Просмотр')],
                        default='viewer',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='family_memberships',
                        to='auth.group',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='family_memberships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Участник семейной группы',
                'verbose_name_plural': 'Участники семейных групп',
            },
        ),
        migrations.AddConstraint(
            model_name='familygroupmembership',
            constraint=models.UniqueConstraint(
                fields=('group', 'user'),
                name='unique_family_group_membership',
            ),
        ),
        migrations.RunPython(seed_family_memberships, migrations.RunPython.noop),
    ]
