# Generated by Django 6.0.5 on 2026-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_family_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementupload",
            name="skipped_count",
            field=models.IntegerField(default=0),
        ),
    ]
