# Generated by Django 6.0.5 on 2026-06-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_bankstatementupload_skipped_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyinvite",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
