# Generated by Django 6.0.6 on 2026-06-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_invite_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementupload",
            name="account_balance_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Остаток в приложении после импорта",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementupload",
            name="balance_discrepancy",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Расхождение баланса",
            ),
        ),
        migrations.AddField(
            model_name="bankstatementupload",
            name="statement_closing_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Остаток по выписке",
            ),
        ),
    ]
