# Generated by Django 6.0.7 on 2026-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0017_alter_transfermoneylog_from_account_and_more"),
        ("users", "0010_bankstatementupload_reconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementupload",
            name="file_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="bankstatementupload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file_hash", ""), _negated=True),
                fields=("account", "file_hash"),
                name="uniq_statement_account_file_hash",
            ),
        ),
    ]
