# Generated by Django 6.0.7 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_source_file_hash_and_more'),
        ('users', '0011_bankstatementupload_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatementupload',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'В очереди'),
                    ('processing', 'Обрабатывается'),
                    ('awaiting_confirmation', 'Ожидает подтверждения'),
                    ('completed', 'Завершено'),
                    ('failed', 'Ошибка'),
                ],
                default='pending',
                max_length=21,
            ),
        ),
        migrations.CreateModel(
            name='BankStatementRow',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'transaction_type',
                    models.CharField(
                        choices=[('income', 'Доход'), ('expense', 'Расход')],
                        max_length=10,
                    ),
                ),
                ('transaction_date', models.DateTimeField()),
                (
                    'amount',
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ('description', models.CharField(max_length=250)),
                ('candidate_description', models.CharField(max_length=250)),
                ('suggested_category', models.CharField(max_length=250)),
                (
                    'source_ref',
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ('source_row_position', models.PositiveIntegerField()),
                (
                    'decision',
                    models.CharField(
                        choices=[
                            ('pending', 'Ожидает решения'),
                            ('linked', 'Уже учтена'),
                            ('new', 'Новая операция'),
                        ],
                        default='pending',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statement_candidates',
                        to='transactions.transaction',
                    ),
                ),
                (
                    'transaction',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statement_rows',
                        to='transactions.transaction',
                    ),
                ),
                (
                    'upload',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statement_rows',
                        to='users.bankstatementupload',
                    ),
                ),
            ],
            options={
                'ordering': ['transaction_date', 'pk'],
                'indexes': [
                    models.Index(
                        fields=['upload', 'decision'],
                        name='users_statement_decision_idx',
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('upload', 'source_row_position'),
                        name='unique_statement_upload_row',
                    ),
                ],
            },
        ),
    ]
