# Generated by Django 6.0.7 on 2026-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_seed_statement_cleanup_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone_name",
            field=models.CharField(default="Europe/Moscow", max_length=64),
        ),
    ]
