# Generated by Django 6.0.7 on 2026-09-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance_account', '0024_add_external_id_and_audit'),
        ('transactions', '0004_transaction_description'),
        ('users', '0017_user_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementrow',
            name='transfer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='statement_rows',
                to='finance_account.transfermoneylog',
            ),
        ),
        migrations.AddField(
            model_name='bankstatementupload',
            name='needs_transfer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankstatementdecisionaudit',
            name='decision',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает решения'),
                    ('linked', 'Уже учтена'),
                    ('new', 'Новая операция'),
                    ('needs_transfer', 'Нужен перевод'),
                    ('transferred', 'Уже учтена'),
                    ('not_a_payment', 'Не погашение'),
                    ('expired', 'Срок решения истёк'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='bankstatementrow',
            name='decision',
            field=models.CharField(
                choices=[
                    ('pending', 'Ожидает решения'),
                    ('linked', 'Уже учтена'),
                    ('new', 'Новая операция'),
                    ('needs_transfer', 'Нужен перевод'),
                    ('transferred', 'Уже учтена'),
                    ('not_a_payment', 'Не погашение'),
                    ('expired', 'Срок решения истёк'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='bankstatementrow',
            constraint=models.UniqueConstraint(
                condition=models.Q(('transfer__isnull', False)),
                fields=('transfer',),
                name='unique_statement_row_transfer',
            ),
        ),
    ]
