# Generated by Django 6.0.7 on 2026-09-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance_account', '0024_add_external_id_and_audit'),
        ('transactions', '0004_transaction_description'),
        ('users', '0018_bankstatementrow_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankstatementrow',
            name='unique_statement_row_transfer',
        ),
        migrations.AddField(
            model_name='bankstatementcandidate',
            name='transfer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='statement_candidate_links',
                to='finance_account.transfermoneylog',
            ),
        ),
        migrations.AddField(
            model_name='bankstatementdecisionaudit',
            name='previous_transfer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='previous_statement_decision_audits',
                to='finance_account.transfermoneylog',
            ),
        ),
        migrations.AddField(
            model_name='bankstatementdecisionaudit',
            name='transfer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='statement_decision_audits',
                to='finance_account.transfermoneylog',
            ),
        ),
        migrations.AddConstraint(
            model_name='bankstatementcandidate',
            constraint=models.UniqueConstraint(
                condition=models.Q(('transfer__isnull', False)),
                fields=('row', 'transfer'),
                name='unique_statement_row_transfer_candidate',
            ),
        ),
        migrations.AddConstraint(
            model_name='bankstatementrow',
            constraint=models.UniqueConstraint(
                condition=models.Q(('transfer__isnull', False)),
                fields=('transfer', 'transaction_type'),
                name='unique_statement_row_transfer',
            ),
        ),
    ]
