# Generated by Django 6.0.7 on 2026-09-10 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_add_object_name_to_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Журнал аудита",
                "verbose_name_plural": "Журнал аудита",
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transfer", "Перевод"),
                    ("receipt_purchase", "Чек"),
                    ("income", "Доход"),
                    ("expense", "Расход"),
                    ("transaction_edit", "Правка транзакции"),
                    ("transaction_delete", "Удаление транзакции"),
                    ("receipt_edit", "Правка чека"),
                    ("receipt_delete", "Удаление чека"),
                    ("account_edit", "Правка счёта"),
                    ("account_delete", "Удаление счёта"),
                    ("statement_import", "Импорт выписки"),
                    ("statement_import_resolution", "Разбор нерешённых строк"),
                ],
                max_length=30,
                null=True,
                verbose_name="Вид операции",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="operation_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Идентификатор операции"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["operation_id"], name="system_audi_operati_859e05_idx"
            ),
        ),
    ]
