# Generated by Django 6.0.5 on 2026-05-27 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0017_alter_transfermoneylog_from_account_and_more"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source_ref",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Идентификатор операции в выписке",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "source_ref"], name="transaction_account_989426_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_ref__isnull", False)),
                fields=("account", "source_ref"),
                name="unique_account_source_ref",
            ),
        ),
    ]
