# Generated by Django 6.0.7 on 2026-07-29 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0017_alter_transfermoneylog_from_account_and_more"),
        ("transactions", "0002_transaction_source_ref_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source_file_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_row_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "source_file_hash", "source_row_position"],
                name="transaction_account_ea5d68_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_file_hash__isnull", False)),
                fields=("account", "source_file_hash", "source_row_position"),
                name="unique_statement_source_row",
            ),
        ),
    ]
