# Generated by Django 6.0.7 on 2026-08-01 14:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_account', '0018_alter_account_type_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название вклада')),
                ('bank', models.CharField(choices=[('-', '—'), ('SBERBANK', 'Сбербанк'), ('RAIFFAISENBANK', 'Райффайзенбанк')], max_length=20, verbose_name='Банк')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='finance_account.account')),
            ],
            options={
                'verbose_name': 'Срочный вклад',
                'verbose_name_plural': 'Срочные вклады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepositTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_on', models.DateField(verbose_name='Дата открытия')),
                ('matures_on', models.DateField(verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='deposits.deposit')),
            ],
            options={
                'ordering': ['opened_on'],
            },
        ),
        migrations.CreateModel(
            name='DepositRatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(verbose_name='Начало периода ставки')),
                ('ends_on', models.DateField(verbose_name='Окончание периода ставки')),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Годовая ставка')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_periods', to='deposits.depositterm')),
            ],
            options={
                'ordering': ['starts_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='depositterm',
            constraint=models.CheckConstraint(condition=models.Q(('matures_on__gte', models.F('opened_on'))), name='deposit_term_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='depositterm',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('deposit',), name='one_current_term_per_deposit'),
        ),
        migrations.AddConstraint(
            model_name='depositrateperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='deposit_rate_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='depositrateperiod',
            constraint=models.CheckConstraint(condition=models.Q(('annual_rate__gt', 0)), name='deposit_annual_rate_positive'),
        ),
    ]
