# Generated by Django 6.0.7 on 2026-08-01 15:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
        ('finance_account', '0018_alter_account_type_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositPrincipalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('funding', 'Финансирование'), ('opening_position', 'Начальная позиция')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_on', models.DateField(verbose_name='Дата события')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principal_events', to='deposits.deposit')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_funding_events', to='finance_account.account')),
            ],
            options={
                'ordering': ['effective_on', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('type', 'funding')), models.Q(('amount__gte', 0), ('type', 'opening_position')), _connector='OR'), name='deposit_principal_event_amount_valid'), models.CheckConstraint(condition=models.Q(models.Q(('source_account__isnull', False), ('type', 'funding')), models.Q(('source_account__isnull', True), ('type', 'opening_position')), _connector='OR'), name='deposit_principal_event_source_valid')],
            },
        ),
    ]
