# Generated by Django 6.0.7 on 2026-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0002_depositprincipalevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositrateperiod",
            name="note",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                verbose_name="Пояснение к ставке",
            ),
        ),
        migrations.AddField(
            model_name="depositterm",
            name="rate_kind",
            field=models.CharField(
                choices=[("fixed", "Фиксированная"), ("floating", "Плавающая")],
                default="fixed",
                max_length=10,
                verbose_name="Тип ставки",
            ),
        ),
    ]
