# Generated by Django 6.0.7 on 2026-08-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0003_rate_kind_and_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositterm",
            name="accrual_end_included",
            field=models.BooleanField(
                default=False, verbose_name="Учитывать день возврата вклада"
            ),
        ),
        migrations.AddField(
            model_name="depositterm",
            name="accrual_start_included",
            field=models.BooleanField(
                default=True, verbose_name="Учитывать день поступления средств"
            ),
        ),
        migrations.AddField(
            model_name="depositterm",
            name="business_day_convention",
            field=models.CharField(
                choices=[
                    ("none", "Без переноса"),
                    ("preceding", "На предыдущий рабочий день"),
                    ("following", "На следующий рабочий день"),
                ],
                default="none",
                max_length=10,
                verbose_name="Перенос выплаты на рабочий день",
            ),
        ),
        migrations.AddField(
            model_name="depositterm",
            name="day_count_convention",
            field=models.CharField(
                choices=[
                    ("actual_actual", "Actual/Actual"),
                    ("actual_365", "Actual/365"),
                ],
                default="actual_actual",
                max_length=20,
                verbose_name="Метод расчёта дней",
            ),
        ),
        migrations.AddField(
            model_name="depositterm",
            name="payout_schedule_kind",
            field=models.CharField(
                choices=[
                    ("monthly", "Ежемесячно"),
                    ("maturity", "В конце срока"),
                    ("custom", "Индивидуальное расписание"),
                ],
                default="maturity",
                max_length=10,
                verbose_name="Расписание выплат",
            ),
        ),
        migrations.CreateModel(
            name="DepositInterestForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payout_on", models.DateField(verbose_name="Ожидаемая дата выплаты")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Ожидаемая сумма"
                    ),
                ),
                (
                    "period_starts_on",
                    models.DateField(verbose_name="Начало периода начисления"),
                ),
                (
                    "period_ends_on",
                    models.DateField(verbose_name="Конец периода начисления"),
                ),
                (
                    "is_rate_undefined",
                    models.BooleanField(
                        default=False, verbose_name="Ставка периода не определена"
                    ),
                ),
                (
                    "is_date_tentative",
                    models.BooleanField(
                        default=False, verbose_name="Дата ориентировочна"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Подтверждено фактической выплатой"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_forecasts",
                        to="deposits.depositterm",
                    ),
                ),
            ],
            options={
                "ordering": ["payout_on", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="deposit_interest_forecast_amount_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_ends_on__gte", models.F("period_starts_on"))
                        ),
                        name="deposit_interest_forecast_period_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DepositPayoutScheduleDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payout_on", models.DateField(verbose_name="Дата выплаты")),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_schedule_dates",
                        to="deposits.depositterm",
                    ),
                ),
            ],
            options={
                "ordering": ["payout_on"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("term", "payout_on"),
                        name="deposit_payout_schedule_date_unique",
                    )
                ],
            },
        ),
    ]
