# Generated by Django 6.0.7 on 2026-08-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_depositterm_accrual_end_included_and_more'),
        ('finance_account', '0018_alter_account_type_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='deposit_principal_event_amount_valid',
        ),
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='deposit_principal_event_source_valid',
        ),
        migrations.AddField(
            model_name='depositprincipalevent',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_withdrawal_events', to='finance_account.account'),
        ),
        migrations.AddField(
            model_name='depositprincipalevent',
            name='exception_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Причина исключения'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='maximum_withdrawal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Максимальная сумма снятия'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='minimum_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Неснижаемый остаток'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='minimum_withdrawal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Минимальная сумма снятия'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='withdrawal_allowed',
            field=models.BooleanField(default=False, verbose_name='Разрешено частичное снятие'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='withdrawal_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срок снятия'),
        ),
        migrations.AlterField(
            model_name='depositprincipalevent',
            name='type',
            field=models.CharField(choices=[('funding', 'Финансирование'), ('opening_position', 'Начальная позиция'), ('withdrawal', 'Снятие')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('type', 'funding')), models.Q(('amount__gte', 0), ('type', 'opening_position')), models.Q(('amount__gt', 0), ('type', 'withdrawal')), _connector='OR'), name='deposit_principal_event_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_account__isnull', False), ('type', 'funding')), models.Q(('source_account__isnull', True), ('type', 'opening_position')), models.Q(('destination_account__isnull', False), ('source_account__isnull', True), ('type', 'withdrawal')), _connector='OR'), name='deposit_principal_event_source_valid'),
        ),
    ]
