# Generated by Django 6.0.7 on 2026-08-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('deposits', '0005_add_withdrawal_terms'),
        ('finance_account', '0018_alter_account_type_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='deposit_principal_event_amount_valid',
        ),
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='deposit_principal_event_source_valid',
        ),
        migrations.AddField(
            model_name='depositterm',
            name='maximum_balance',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name='Максимальный остаток после пополнения',
            ),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='maximum_top_up_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name='Максимальная сумма пополнения',
            ),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='minimum_top_up_amount',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name='Минимальная сумма пополнения',
            ),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='top_up_allowed',
            field=models.BooleanField(
                default=False, verbose_name='Разрешено пополнение'
            ),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='top_up_deadline',
            field=models.DateField(
                blank=True, null=True, verbose_name='Крайний срок пополнения'
            ),
        ),
        migrations.AlterField(
            model_name='depositprincipalevent',
            name='type',
            field=models.CharField(
                choices=[
                    ('funding', 'Финансирование'),
                    ('opening_position', 'Начальная позиция'),
                    ('top_up', 'Пополнение'),
                    ('withdrawal', 'Снятие'),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('amount__gt', 0), ('type', 'funding')),
                    models.Q(('amount__gte', 0), ('type', 'opening_position')),
                    models.Q(('amount__gt', 0), ('type', 'top_up')),
                    models.Q(('amount__gt', 0), ('type', 'withdrawal')),
                    _connector='OR',
                ),
                name='deposit_principal_event_amount_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('source_account__isnull', False), ('type', 'funding')
                    ),
                    models.Q(
                        ('source_account__isnull', False), ('type', 'top_up')
                    ),
                    models.Q(
                        ('source_account__isnull', True),
                        ('type', 'opening_position'),
                    ),
                    models.Q(
                        ('destination_account__isnull', False),
                        ('source_account__isnull', True),
                        ('type', 'withdrawal'),
                    ),
                    _connector='OR',
                ),
                name='deposit_principal_event_source_valid',
            ),
        ),
    ]
