# Generated by Django 6.0.7 on 2026-08-02 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_add_top_up_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCapitalizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('withholding', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('net', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('posting_on', models.DateField(verbose_name='Дата проводки')),
                ('value_on', models.DateField(verbose_name='Дата валютирования')),
                ('reason', models.CharField(blank=True, default='', max_length=250, verbose_name='Причина внеплановой капитализации')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitalization_events', to='deposits.deposit')),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capitalization_event', to='deposits.depositinterestforecast')),
            ],
            options={
                'ordering': ['value_on', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('gross__gte', 0)), name='deposit_capitalization_gross_non_negative'), models.CheckConstraint(condition=models.Q(('withholding__gte', 0)), name='deposit_capitalization_withholding_non_negative'), models.CheckConstraint(condition=models.Q(('net__gte', 0)), name='deposit_capitalization_net_non_negative')],
            },
        ),
    ]
