# Generated by Django 6.0.7 on 2026-08-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0009_add_bank_default"),
        ("finance_account", "0022_add_bank_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deposits",
                to="finance_account.bank",
                verbose_name="Банк",
            ),
        ),
    ]
