# Generated by Django 6.0.7 on 2026-08-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('deposits', '0010_alter_deposit_bank'),
        ('finance_account', '0022_add_bank_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositcapitalizationevent',
            name='destination',
            field=models.CharField(
                choices=[
                    ('capitalization', 'Капитализация'),
                    ('internal_account', 'На собственный счёт'),
                    ('external', 'Внешнему получателю'),
                ],
                default='capitalization',
                max_length=20,
                verbose_name='Фактическое назначение выплаты',
            ),
        ),
        migrations.AlterField(
            model_name='depositcapitalizationevent',
            name='reason',
            field=models.CharField(
                blank=True,
                default='',
                max_length=250,
                verbose_name='Причина внеплановой выплаты',
            ),
        ),
        migrations.AddField(
            model_name='depositcapitalizationevent',
            name='destination_account',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='deposit_interest_payouts',
                to='finance_account.account',
                verbose_name='Счёт назначения',
            ),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='interest_payout_destination',
            field=models.CharField(
                choices=[
                    ('capitalization', 'Капитализация'),
                    ('internal_account', 'На собственный счёт'),
                    ('external', 'Внешнему получателю'),
                ],
                default='capitalization',
                max_length=20,
                verbose_name='Обычный способ выплаты процентов',
            ),
        ),
        migrations.AddConstraint(
            model_name='depositcapitalizationevent',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('destination', 'internal_account'),
                        ('destination_account__isnull', False),
                    ),
                    models.Q(
                        ('destination__in', ('capitalization', 'external')),
                        ('destination_account__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='deposit_interest_destination_account_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='depositcapitalizationevent',
            constraint=models.UniqueConstraint(
                condition=models.Q(('forecast__isnull', False)),
                fields=('forecast',),
                name='one_actual_interest_event_per_forecast',
            ),
        ),
    ]
