# Generated by Django 6.0.7 on 2026-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0011_add_interest_payout_destinations"),
        ("finance_account", "0023_account_archived_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="depositprincipalevent",
            name="deposit_principal_event_amount_valid",
        ),
        migrations.RemoveConstraint(
            model_name="depositprincipalevent",
            name="deposit_principal_event_source_valid",
        ),
        migrations.AddField(
            model_name="depositcapitalizationevent",
            name="is_final",
            field=models.BooleanField(
                default=False, verbose_name="Финальная выплата при закрытии"
            ),
        ),
        migrations.AddField(
            model_name="depositprincipalevent",
            name="destination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("capitalization", "Капитализация"),
                    ("internal_account", "На собственный счёт"),
                    ("external", "Внешнему получателю"),
                ],
                max_length=20,
                null=True,
                verbose_name="Назначение возврата тела",
            ),
        ),
        migrations.AddField(
            model_name="depositprincipalevent",
            name="posting_on",
            field=models.DateField(blank=True, null=True, verbose_name="Дата проводки"),
        ),
        migrations.AddField(
            model_name="depositterm",
            name="closed_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Фактическая дата закрытия"
            ),
        ),
        migrations.AlterField(
            model_name="depositprincipalevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("funding", "Финансирование"),
                    ("opening_position", "Начальная позиция"),
                    ("top_up", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("planned_closure", "Плановое закрытие"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="depositcapitalizationevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_final", True)),
                fields=("deposit",),
                name="one_final_interest_event_per_deposit",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositprincipalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("amount__gt", 0), ("type", "funding")),
                    models.Q(("amount__gte", 0), ("type", "opening_position")),
                    models.Q(("amount__gt", 0), ("type", "top_up")),
                    models.Q(("amount__gt", 0), ("type", "withdrawal")),
                    models.Q(("amount__gte", 0), ("type", "planned_closure")),
                    _connector="OR",
                ),
                name="deposit_principal_event_amount_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositprincipalevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_account__isnull", False), ("type", "funding")),
                    models.Q(("source_account__isnull", False), ("type", "top_up")),
                    models.Q(
                        ("source_account__isnull", True), ("type", "opening_position")
                    ),
                    models.Q(
                        ("destination_account__isnull", False),
                        ("source_account__isnull", True),
                        ("type", "withdrawal"),
                    ),
                    models.Q(
                        ("destination", "internal_account"),
                        ("destination_account__isnull", False),
                        ("source_account__isnull", True),
                        ("type", "planned_closure"),
                    ),
                    models.Q(
                        ("destination", "external"),
                        ("destination_account__isnull", True),
                        ("source_account__isnull", True),
                        ("type", "planned_closure"),
                    ),
                    _connector="OR",
                ),
                name="deposit_principal_event_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositprincipalevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "planned_closure")),
                fields=("deposit",),
                name="one_planned_closure_per_deposit",
            ),
        ),
        migrations.AddConstraint(
            model_name="depositterm",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_on__isnull", True),
                    ("closed_on__gte", models.F("matures_on")),
                    _connector="OR",
                ),
                name="planned_deposit_closure_not_before_maturity",
            ),
        ),
    ]
