# Generated by Django 6.0.7 on 2026-08-05 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0012_remove_depositprincipalevent_deposit_principal_event_amount_valid_and_more'),
        ('finance_account', '0023_account_archived_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='deposit_principal_event_amount_valid',
        ),
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='deposit_principal_event_source_valid',
        ),
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='one_planned_closure_per_deposit',
        ),
        migrations.RemoveConstraint(
            model_name='depositterm',
            name='planned_deposit_closure_not_before_maturity',
        ),
        migrations.AddField(
            model_name='depositcapitalizationevent',
            name='prior_interest_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Корректировка ранее выплаченных процентов'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='early_closure_annual_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка досрочного расторжения'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='early_closure_recalculation_scope',
            field=models.CharField(choices=[('whole_term', 'Весь срок'), ('current_period', 'Текущий период'), ('withdrawn_amount', 'Снятая сумма'), ('unsupported', 'Формула банка не поддерживается')], default='unsupported', max_length=20, verbose_name='Область пересчёта при досрочном расторжении'),
        ),
        migrations.AlterField(
            model_name='depositprincipalevent',
            name='type',
            field=models.CharField(choices=[('funding', 'Финансирование'), ('opening_position', 'Начальная позиция'), ('top_up', 'Пополнение'), ('withdrawal', 'Снятие'), ('planned_closure', 'Плановое закрытие'), ('early_closure', 'Досрочное закрытие')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('type', 'funding')), models.Q(('amount__gte', 0), ('type', 'opening_position')), models.Q(('amount__gt', 0), ('type', 'top_up')), models.Q(('amount__gt', 0), ('type', 'withdrawal')), models.Q(('amount__gte', 0), ('type', 'planned_closure')), models.Q(('amount__gte', 0), ('type', 'early_closure')), _connector='OR'), name='deposit_principal_event_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_account__isnull', False), ('type', 'funding')), models.Q(('source_account__isnull', False), ('type', 'top_up')), models.Q(('source_account__isnull', True), ('type', 'opening_position')), models.Q(('destination_account__isnull', False), ('source_account__isnull', True), ('type', 'withdrawal')), models.Q(('destination', 'internal_account'), ('destination_account__isnull', False), ('source_account__isnull', True), ('type', 'planned_closure')), models.Q(('destination', 'external'), ('destination_account__isnull', True), ('source_account__isnull', True), ('type', 'planned_closure')), models.Q(('destination', 'internal_account'), ('destination_account__isnull', False), ('source_account__isnull', True), ('type', 'early_closure')), models.Q(('destination', 'external'), ('destination_account__isnull', True), ('source_account__isnull', True), ('type', 'early_closure')), _connector='OR'), name='deposit_principal_event_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('planned_closure', 'early_closure'))), fields=('deposit',), name='one_closure_per_deposit'),
        ),
        migrations.AddConstraint(
            model_name='depositterm',
            constraint=models.CheckConstraint(condition=models.Q(('closed_on__isnull', True), ('closed_on__gte', models.F('opened_on')), _connector='OR'), name='deposit_closure_not_before_opening'),
        ),
    ]
