# Generated by Django 6.0.7 on 2026-08-05 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0013_remove_depositprincipalevent_deposit_principal_event_amount_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositterm',
            name='early_closure_withdrawn_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма для пересчёта при досрочном расторжении'),
        ),
    ]
