# Generated by Django 6.0.7 on 2026-08-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0014_depositterm_early_closure_withdrawn_amount'),
        ('finance_account', '0023_account_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositprincipalevent',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='deposits.depositprincipalevent', verbose_name='Аннулированное событие'),
        ),
        migrations.AddField(
            model_name='depositprincipalevent',
            name='reversal_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Причина аннулирования'),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('reversal_reason', '')), models.Q(('reversal_of__isnull', False), ('reversal_reason__gt', '')), _connector='OR'), name='deposit_principal_reversal_reason_valid'),
        ),
        migrations.AddField(
            model_name='depositcapitalizationevent',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='deposits.depositcapitalizationevent', verbose_name='Аннулированная выплата'),
        ),
        migrations.AddField(
            model_name='depositcapitalizationevent',
            name='reversal_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Причина аннулирования'),
        ),
        migrations.AddConstraint(
            model_name='depositcapitalizationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('reversal_reason', '')), models.Q(('reversal_of__isnull', False), ('reversal_reason__gt', '')), _connector='OR'), name='deposit_interest_reversal_reason_valid'),
        ),
        migrations.RemoveConstraint(
            model_name='depositcapitalizationevent',
            name='one_final_interest_event_per_deposit',
        ),
        migrations.RemoveConstraint(
            model_name='depositprincipalevent',
            name='one_closure_per_deposit',
        ),
        migrations.CreateModel(
            name='DepositRenewalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_on', models.DateField(verbose_name='Дата пролонгации')),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=250, verbose_name='Причина аннулирования')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_events', to='deposits.deposit')),
                ('previous_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals_from', to='deposits.depositterm')),
                ('renewed_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_events', to='deposits.depositterm')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='deposits.depositrenewalevent', verbose_name='Аннулированная пролонгация')),
            ],
            options={
                'ordering': ['effective_on', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('reversal_reason', '')), models.Q(('reversal_of__isnull', False), ('reversal_reason__gt', '')), _connector='OR'), name='deposit_renewal_reversal_reason_valid')],
            },
        ),
    ]
