# Generated by Django 6.0.7 on 2026-08-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0015_depositprincipalevent_reversal_of_and_more'),
        ('finance_account', '0024_add_external_id_and_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('conversion', 'Преобразование счёта'), ('confirmation', 'Подтверждение выплаты процентов'), ('exclusion', 'Операция вне условий'), ('cancellation', 'Аннулирование события'), ('closure', 'Закрытие вклада'), ('renewal', 'Пролонгация вклада')], max_length=20, verbose_name='Тип операции')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
            ],
            options={
                'verbose_name': 'Запись аудита вклада',
                'verbose_name_plural': 'Аудит вкладов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='depositcapitalizationevent',
            name='external_id',
            field=models.CharField(blank=True, help_text='Уникальный в пределах вклада ключ банковского факта', max_length=250, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AddField(
            model_name='depositprincipalevent',
            name='external_id',
            field=models.CharField(blank=True, help_text='Уникальный в пределах вклада ключ банковского факта', max_length=250, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AddConstraint(
            model_name='depositcapitalizationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('deposit', 'external_id'), name='deposit_interest_external_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='depositprincipalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('deposit', 'external_id'), name='deposit_principal_external_id_unique'),
        ),
        migrations.AddField(
            model_name='depositauditevent',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='deposits.deposit', verbose_name='Вклад'),
        ),
        migrations.AddIndex(
            model_name='depositauditevent',
            index=models.Index(fields=['deposit', 'event_type'], name='deposits_de_deposit_4d9cd3_idx'),
        ),
    ]
