# Generated by Django 6.0.7 on 2026-08-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0016_add_external_id_and_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositterm',
            name='interest_accrual_starts_on',
            field=models.DateField(blank=True, help_text='Если не указана, начисление начинается с даты открытия.', null=True, verbose_name='Дата начала начисления процентов'),
        ),
        migrations.AddField(
            model_name='depositterm',
            name='rounding_rule',
            field=models.CharField(default='ROUND_HALF_UP', help_text='Константа округления из модуля decimal (ROUND_HALF_UP, ROUND_HALF_EVEN и т.д.).', max_length=20, verbose_name='Правило денежного округления'),
        ),
    ]
