# Generated by Django 6.0.7 on 2026-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0017_add_interest_accrual_starts_on_and_rounding"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="depositrateperiod",
            index=models.Index(
                fields=["term", "starts_on", "ends_on"],
                name="deposit_rate_period_range_idx",
            ),
        ),
    ]
