# Generated by Django 6.0.7 on 2026-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0018_depositrateperiod_deposit_rate_period_range_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositauditevent',
            name='event_type',
            field=models.CharField(choices=[('conversion', 'Преобразование счёта'), ('confirmation', 'Подтверждение выплаты процентов'), ('exclusion', 'Операция вне условий'), ('cancellation', 'Аннулирование события'), ('closure', 'Закрытие вклада'), ('renewal', 'Пролонгация вклада'), ('schedule_correction', 'Исправление расписания выплат')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
