# Generated by Django 4.2.17 on 2025-02-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                ('loan_amount', models.FloatField(max_length=250)),
                (
                    'annual_interest_rate',
                    models.DecimalField(decimal_places=2, max_digits=250),
                ),
                ('period_loan', models.IntegerField()),
                (
                    'type_loan',
                    models.CharField(
                        choices=[
                            ('Annuity', 'Аннуитетный'),
                            ('Differentiated', 'Дифференцированный'),
                        ],
                        default='Annuity',
                    ),
                ),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMakeLoan',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=250)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateTimeField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=60)),
                (
                    'monthly_payment',
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                ('interest', models.DecimalField(decimal_places=2, max_digits=60)),
                (
                    'principal_payment',
                    models.DecimalField(decimal_places=2, max_digits=60),
                ),
                (
                    'loan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment_schedule_loans',
                        to='loan.loan',
                    ),
                ),
            ],
        ),
    ]
