# Generated by Django 4.2.17 on 2025-02-09 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance_account', '0002_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payment_schedule_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='paymentmakeloan',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='payment_make_loan_accounts',
                to='finance_account.account',
            ),
        ),
        migrations.AddField(
            model_name='paymentmakeloan',
            name='loan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='loans',
                to='loan.loan',
            ),
        ),
        migrations.AddField(
            model_name='paymentmakeloan',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payment_make_loan_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='loan_accounts',
                to='finance_account.account',
            ),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='loan_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['-id'], name='loan_loan_id_bf4de1_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(
                fields=['loan_amount'], name='loan_loan_loan_am_4dd1a2_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(
                fields=['annual_interest_rate'], name='loan_loan_annual__c669ae_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(
                fields=['period_loan'], name='loan_loan_period__f18127_idx'
            ),
        ),
    ]
