# Generated by Django 5.2.7 on 2025-10-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('loan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='type_loan',
            field=models.CharField(
                choices=[
                    ('Annuity', 'Аннуитетный'),
                    ('Differentiated', 'Дифференцированный'),
                ],
                default='Annuity',
                max_length=20,
            ),
        ),
    ]
