# Generated by Django 6.0.2 on 2026-02-25 11:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_account", "0017_alter_transfermoneylog_from_account_and_more"),
        ("loan", "0003_alter_loan_type_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="annual_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("999.99")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="paymentmakeloan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_make_loan_accounts",
                to="finance_account.account",
            ),
        ),
    ]
