# Generated by Django 5.2.3 on 2025-06-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
    ]
