# Generated by Django 5.2.3 on 2025-06-29 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance_account', '0006_alter_account_created_at'),
        ('income', '0003_alter_income_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='income',
            name='income_inco_date_2adb4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='income_inco_amount_358474_idx',
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(
                fields=['user', 'date'], name='income_inco_user_id_f74de7_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(
                fields=['user', 'category'], name='income_inco_user_id_04ffe9_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(
                fields=['user', 'account'], name='income_inco_user_id_b25db4_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(
                fields=['date', 'amount'], name='income_inco_date_8ef77e_idx'
            ),
        ),
    ]
