# Generated by Django 5.2.4 on 2025-07-08 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance_account', '0009_account_grace_period_days'),
        ('income', '0004_remove_income_income_inco_date_2adb4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['-date'], name='income_inco_date_2adb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['amount'], name='income_inco_amount_358474_idx'),
        ),
    ]
