site_name: Hasta La Vista, Money!
repo_url: https://github.com/hlvm-app/hasta-la-vista-money.git
edit_uri: edit/main/docs/
nav:
  - Getting started:
      - Installation: index.md
      - Contribute: contribute.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"

      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: 'source'


copyright: '© Alexander Pavlov 2022-2024'
site_author: 'Alexander Pavlov'
site_description: 'Navigation:'
