site_name: Hasta La Vista, Money!
repo_url: https://github.com/hlvm-app/hasta-la-vista-money.git
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Hasta la Vista, Money:
    - Quick start:
      - Installation: index.md
      - Registration: registration.md
    - Getting Started:
      - User Management:
        - Users Documentation: users/users_documentation.md
      - Accounts management page:
        - Account Summary Page: finance_account/finance_account.md
      - Receipts management page:
        - Quick Start: receipts/quick_start.md
        - Receipts Page: receipts/receipts_page.md
        - Add receipts with AI: receipts/processing_receipt_ai.md
        - Developer Guide: receipts/development.md
      - Expenses management page:
        - Expenses Page: expenses/expenses_page.md
      - Income management page:
        - Income Page: income/income_page.md
  - API Documentation:
      - API Overview: api/api_documentation.md
  - Contribute:
      contribute.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
  favicon: icon/favicon.png
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            members_order: 'source'
  - render_swagger:
      allow_arbitrary_locations: true


site_author: 'Alexander Pavlov'
site_description: 'Hasta la Vista, Money!' 
