site_name: Hasta La Vista, Money!
nav:
  - Home: index.md
  - Вклад в проект: install.md
  - Account app: account.md
theme:
  name: mkdocs
  locale: ru
  user_color_mode_toggle: true
  color_mode: auto
  nav_style: dark

plugins:
  - mkdocstrings

copyright: '© Alexander Pavlov 2022-2024'
site_author: 'Alexander Pavlov'
site_description: 'Hasta La Vista, Money!'