name: Bandit

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "**"]
  schedule:
    - cron: '34 8 * * 1'

jobs:
  bandit:
    runs-on: docker
    container:
      image: git.pavlovteam.ru/turtleold/ci-base:3.14
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Bandit
        run: bandit -r . -x .venv,venv,tests -ll --exit-zero
