name: Dokku

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Push to dokku
      uses: dokku/github-action@master
      with:
        git_remote_url: 'ssh://dokku@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}/hlvm'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        git_push_flags: '--force'
        trace: '1'
